### ISSUE TITLE
setup运行失败

### ISSUE THREAD

**Issue by JL13sky** [jiangjh0908/Yolov8_with_DCNv3#10]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

setup运行失败
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]                               
   or: setup.py --help-commands                                      
   or: setup.py cmd --help
求解！谢谢

**Comment by jiangjh0908** [comment]
@JL13sky 尝试下python setup.py install

**Comment by JL13sky** [comment]
> @JL13sky 尝试下python setup.py install

谢谢！已解决！
