### ISSUE TITLE
删除调试信息

### ISSUE THREAD

**Issue by 1104358653** [jiangjh0908/Yolov8_with_DCNv3#9]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 288, 21, 21]) 输入： torch.Size([8, 288, 21, 21]) 这个信息在哪个文件一直没找到，

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jiangjh0908** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.
> 
> ### Description
> 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 96, 84, 84]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 192, 42, 42]) 输入： torch.Size([8, 288, 21, 21]) 输入： torch.Size([8, 288, 21, 21]) 这个信息在哪个文件一直没找到，
> 
> ### Use case
> _No response_
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I'd like to help by submitting a PR!

在ultralytics/nn/modules/block.py 中的第384行
![image](https://github.com/jiangjh0908/Yolov8_with_DCNv3/assets/144425299/b8f4dbd7-3fac-4651-bbe6-fdb7116997aa)
